# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-CPANpm
version:      0.009
version_from: lib/Test/CPANpm.pm
installdirs:  site
requires:
    CPAN:                          1.59_54
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
